In [1]:
import os
import cv2
import json
import matplotlib.pyplot as plt
import numpy as np

home_path=os.path.expanduser('~')
mask_dir=os.path.join(home_path, 'weapons/googleguns/annotations/consolidated-annotation/output')
json_ann_dir=os.path.join(home_path, 'weapons/googleguns/annotations/consolidated-annotation/consolidation-response/iteration-1')

In [23]:
def get_contours(img, color):
    lower_color = np.array(color)-3
    upper_color = np.array(color)
    
    mask_color = cv2.inRange(img, lower_color, upper_color)
    contours, hierarchy = cv2.findContours(mask_color, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    '''
    if contours:
        img_con = cv2.drawContours(img, contours, -1, (0, 255, 0), 3)
        cv2.imshow("test", img_con)
        cv2.waitKey(0)
        cv2.destroyAllWindows()
    '''
    return contours

In [3]:
def get_img(s3_path):
    splitted = s3_path.split('/')
    img_local_path = '/'.join(splitted[2:])
    img_full_path = os.path.join(home_path, img_local_path)
    img = cv2.imread(img_full_path)
    return img
    

In [22]:
for x, json_file in enumerate(os.listdir(json_ann_dir)):
    with open(os.path.join(json_ann_dir, json_file)) as f:
        json_data = json.load(f)[0]
        
        if x in [32]:
            s3_path = json_data['consolidatedAnnotation']['content']['googleguns-ref']
            for i in range(2,3):
                info = json_data['consolidatedAnnotation']['content']['googleguns-ref-metadata']['internal-color-map'][str(i)]
                color_info = info['hex-color'][1:]
                int_color_info = int(color_info, 16) 
                r_col =  (int_color_info & 0xff0000) >> 16
                g_col = (int_color_info & 0xff00) >> 8
                b_col = int_color_info & 0xff
                color = [b_col, g_col, r_col]
                img = get_img(s3_path)
                contours = get_contours(img, color)
                for contour in contours:
                    print("##################")
                    print(np.squeeze(np.array(contour),1))

[177 116  28] [180 119  31]
##################
[[188 311]
 [188 313]]
##################
[[514 265]
 [513 266]
 [511 266]
 [510 267]
 [507 267]
 [506 268]
 [504 268]
 [503 269]
 [501 269]
 [500 270]
 [498 270]
 [497 271]
 [495 271]
 [494 272]
 [492 272]
 [491 273]
 [489 273]
 [488 274]
 [486 274]
 [485 275]
 [483 275]
 [482 276]
 [480 276]
 [479 277]
 [477 277]
 [476 278]
 [474 278]
 [473 279]
 [472 279]
 [471 280]
 [469 280]
 [468 281]
 [466 281]
 [465 282]
 [464 282]
 [465 283]
 [465 289]
 [481 289]
 [481 288]
 [482 287]
 [482 285]
 [479 285]
 [478 284]
 [473 284]
 [471 282]
 [472 281]
 [475 281]
 [476 280]
 [479 280]
 [480 279]
 [483 279]
 [484 278]
 [486 278]
 [487 277]
 [489 277]
 [490 276]
 [492 276]
 [493 275]
 [496 275]
 [497 274]
 [499 274]
 [500 273]
 [502 273]
 [503 272]
 [505 272]
 [506 271]
 [508 271]
 [509 270]
 [511 270]
 [512 269]
 [514 269]
 [514 267]
 [515 266]
 [515 265]]
##################
[[184 258]
 [184 306]
 [185 306]
 [187 308]
 [187 303]
 [186 302]
 [186 296]
